services:
  tictactoe:
    image: tictactoe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - GameSettings__BoardSize=3
      - GameSettings__WinCondition=3
    volumes:
      - tictactoe-data:/app/data

volumes:
  tictactoe-data:
